version: "3.8"

services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tecsusDB
      - MYSQL_ROOT_PASSWORD=tecsus
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  mysql_data:
    driver: local
